spring.application.name=stok-yonetim

# Kalıcı Hafıza İçin PostgreSQL Veri Tabanı Bağlantı Ayarları 🐘
spring.datasource.url=jdbc:postgresql://localhost:5432/stok_yonetim
spring.datasource.username=postgres
# ⚠️ KRİTİK NOT: Kurulum yaparken koyduğun şifre 'admin123' değilse burayı kendi şifrenle değiştir tatlım:
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA Ayarları (Tabloları PostgreSQL'de otomatik oluşturan sihirbaz)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# YENİ SÜRÜM UYUMLU SABIT SIFRE AYARLARI (Postman Giriş Bilgilerin)
spring.security.user.name=admin
spring.security.user.password=admin123