spring.application.name=stok-yonetim

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_management
spring.datasource.username=senior_dev
spring.datasource.password=SecurePassword123!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true