server.port=8082

spring.application.name=stok-yonetim

# PostgreSQL Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/stok_yonetim
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Güvenlik Ayarları
spring.security.user.name=admin
spring.security.user.password=admin123